import os
from groq import Groq

_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

_SYSTEM_PROMPT = """You are an expert AI-generated text detector.

Analyze the provided text and score how likely it is to have been generated by an AI language model.

Look for these AI indicators:
- Uniformly structured sentences with little variation in length or rhythm
- Absence of personal voice, authentic emotion, or idiosyncratic word choice
- Formulaic transitions and predictable paragraph structure
- Comprehensive, encyclopedic coverage without a clear personal perspective
- Lack of natural errors, colloquialisms, or spontaneous digressions

Respond with ONLY a single decimal number between 0.0 and 1.0.
0.0 = Almost certainly written by a human.
1.0 = Almost certainly generated by an AI.

Do not include any explanation or extra text. Output the number only."""


def classify_with_llm(text: str) -> float:
    """
    Signal 1 — LLM Classifier (Semantic).

    Sends `text` to the Groq LLM with a scoring prompt and parses the
    returned float.

    Args:
        text: The content to evaluate.

    Returns:
        A float in [0.0, 1.0] where 0.0 is Likely Human and 1.0 is Likely AI.

    Raises:
        RuntimeError: If the Groq API call fails unexpectedly.
    """
    try:
        response = _client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": f"Analyze this text:\n\n{text}"},
            ],
            max_tokens=10,
            temperature=0.0,
        )

        raw = response.choices[0].message.content.strip()
        score = float(raw)
        return max(0.0, min(1.0, score))  # clamp to valid range

    except ValueError:
        # Model returned something non-numeric; fall back to neutral
        return 0.5
    except Exception as exc:
        raise RuntimeError(f"LLM classifier request failed: {exc}") from exc
